### ISSUE TITLE
Loading modules in fsx

### ISSUE THREAD

**Issue by marcellourbani** [dsyme/learn-fsharp#2]
To load FSharp.Data In the fsx playground I had to add a  #r directive. This was a bit hard to find out for a novice, I think it deserves a mention in the task definition. Will send a PR shortly

```F#
// first attempt was with hardcoded path, works but is pretty bad
// #r "/home/user/.nuget/packages/fsharp.data/4.1.1/lib/netstandard2.0/FSharp.Data.dll"
#r "nuget:FSharp.Data"
open FSharp.Data
```

Thanks for this tutorial, was good fun

**Comment by dsyme** [comment]
> To load FSharp.Data In the fsx playground I had to add a #r directive. This was a bit hard to find out for a novice, I think it deserves a mention in the task definition. Will send a PR shortly

Yes in the tutorial I taught Guido to go and look at https://nuget.org and search for a package at this point, which includes a tab containing the reference text.

![image](https://user-images.githubusercontent.com/7204669/128507553-395b9fa9-c9e7-413e-9601-b12dad5bc244.png)

This introduces the user to the package ecosystem.
